swagger: "2.0"
info:
  description: "Auto Mart is an online market place for automobiles of diverse makes, model, or body type. With Auto Mark, users can sell their cars or buy from trusted dealerships or private sellers"
  version: "1.0.0"
  title: "Auto Mart"
  contact:
    email: "alliolaoluwa@gmail.com"
host: "locahost:5500"
basePath: "/api/v1"
tags:
- name: "cars"
  description: "Inventory of Automobiles for sale"
- name: "orders"
  description: "Deals, Transactions to buy cars"
- name: "users"
  description: "Registered users can buy and sell cars"
schemes:
- "http"
paths:
  /cars:
    post:
      tags:
      - "cars"
      summary: "Creates a car ad sale"
      description: "Adds a created car ad sale to te inventory of cars collection"
      parameters:
      - in: "body"
        name: "car"
      description: "The car ad to create"
      schema:
        $ref: "#/definitions/car"
      responses:
        200:
          description: "car ad succesfully created"
        400:
          description: "invalid input"
definitions:
  user:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      email:
        type: "string"
      fistName:
        type: "string"
      lastName:
        type: "string"
      password:
        type: "string"
      address:
        type: "string"
      is_admin:
        type: "string"
        default: false
  users:
    type: "array"
    items:
      $ref: "#/definitions/user"
  car:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      owner:
        type: "integer"
        format: "int64"
      createdOn:
        type: "string"
        format: "date"
      state:
        type: "string"
      status:
        type: "string"
      price:
        type: "number"
        format: "float"
      manufacturer:
        type: "string"
      model:
        type: "string"
      body:
        type: "string"
  cars:
    type: "array"
    items:
      $ref: "#/definitions/car"